### ISSUE TITLE
Compilation error on Linux: "no viable conversion"

### ISSUE THREAD

**Issue by xiota** [shiiion/dolphin#165]
Introduced by e763a70f14f76c9364765fe32e6ebe50ff9b423e (edited to correct commit reference).

```
dolphin-emu-primehack/Source/Core/InputCommon/XInput2Mouse.cpp:36:25: error: no viable conversion from 'XInput2Mouse' to 'pointer' (aka 'prime::GenericMouse *')
   36 |     g_mouse_input.reset(XInput2Mouse((Window)hwnd, xi_opcode, current_master->deviceid));
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/unique_ptr.h:505:21: note: passing argument to parameter '__p' here
  505 |       reset(pointer __p = pointer()) noexcept
      |                     ^
1 error generated.
```
